# Spring Application Name
spring:
  application:
    name: appnumber

# Server Port
server:
  port: 8081

# Logging pattern for the console
# Logging pattern for file
logging:
  file:
    path: logs
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'